version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - GOOGLE_API_KEY=
      - DATABASE_URL=
      - DIRECT_URL=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
